### ISSUE TITLE
After React Native 0.20 Update Wheel is Missing

### ISSUE THREAD

**Issue by BigPun86** [shexiaoheng/react-native-wheel#1]
I imported the exact example like in the example. It use to work RN < 19 but since i updated it it just disappeared

![screenshot_2016-02-22-17-21-29](https://cloud.githubusercontent.com/assets/7880624/13224446/e4c69c46-d988-11e5-84f3-7ddc814fd1b5.png)

**Comment by shexiaoheng** [comment]
@BigPun86 you can try [react-native-picker](https://github.com/beefe/react-native-picker)

**Comment by BigPun86** [comment]
Okay thanks! I am using a classic dropdown at present, but for future projects i will consider using your mentioned module

**Comment by shexiaoheng** [comment]
:smile:

**Comment by BigPun86** [comment]
![image](https://cloud.githubusercontent.com/assets/7880624/13251107/76ea4744-da2e-11e5-8c36-dd2087f21ee0.png)

**Comment by shexiaoheng** [comment]
@BigPun86 Now, already support RN latest version :smile:
