### ISSUE TITLE
about the install

### ISSUE THREAD

**Issue by woshizja** [shexiaoheng/react-native-wheel#2]
I  followed the instructions in Readme, but I got an error while “react-native run-android”：

> A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-wheel : Configuration with name 'default' not found.

This is caused by “settings.gradle”：

> include ':react-native-wheel'
project(':react-native-wheel').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wheel')

I do like this：

> project(':react-native-wheel').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wheel/android')

then problem solved！

By the way，I think “Register React Package” should be done in the file：`MainApplication.java` ，not the `MainActivity.java`.
I register in the `MainActivity.java`, then an other error:

> Execution failed for task ':app:dexDebug'.
> outDexFolder must be a folder

**Comment by shexiaoheng** [comment]
Sorry, the previous document is old . Now I have finished updating .
